name: Publicacion_Horaria_Facebook

on:
  schedule:
    - cron: '0 * * * *'  # Se ejecuta al minuto 0 de cada hora
  workflow_dispatch:      # Botón para probarlo manualmente

jobs:
  publicar_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - env:
          FB_TOKEN: ${{ secrets.EAA7XFZC1ikewBQ6gw93ZBVWDBQQw5CpoNDKJkDXwepEA5tH6bFDQPrlgniIyO3eV4BZBWuxfgzxVmZAqM64eMwZAfAwuKCEHRRKso4vlJMQCVV4yvhSKSyE4sCdNWzZCTNvWZBbhA1KciZACOj9Qrl750kl3lWhNuhgNz13EXZCr9vYZAQqqA9ZCRApkfl3nf3LzXBktc2c4LFe0cp5WsYrufm30z8YWFd3H1LnoH9uYfmuzHoZD}}
        run: python script_clima.py
